import {
  Cat, Dog, Bird, Fish, Rabbit, Squirrel, Snail, Bug, Turtle, Rat,
  Apple, Banana, Cherry, Grape, Carrot, Citrus, Croissant, IceCream, Pizza, Egg,
  Car, Bus, Bike, Plane, Ship, Train, Truck, Rocket, Sailboat, Tractor,
  House, Bed, Lamp, Sofa, DoorOpen, Key, Clock, Scissors, Hammer, Wrench,
  Sun, Moon, Cloud, Star, Tree, Flower, Leaf, Mountain, Snowflake, Umbrella,
  Heart, Phone, Book, Camera, Music, Gift, Anchor, Crown,
  type LucideIcon,
} from "lucide-react";

export type IconItem = { id: string; label: string; Icon: LucideIcon };

export const ICONS: IconItem[] = [
  { id: "cat", label: "Cat", Icon: Cat },
  { id: "dog", label: "Dog", Icon: Dog },
  { id: "bird", label: "Bird", Icon: Bird },
  { id: "fish", label: "Fish", Icon: Fish },
  { id: "rabbit", label: "Rabbit", Icon: Rabbit },
  { id: "squirrel", label: "Squirrel", Icon: Squirrel },
  { id: "snail", label: "Snail", Icon: Snail },
  { id: "bug", label: "Bug", Icon: Bug },
  { id: "turtle", label: "Turtle", Icon: Turtle },
  { id: "rat", label: "Mouse", Icon: Rat },
  { id: "apple", label: "Apple", Icon: Apple },
  { id: "banana", label: "Banana", Icon: Banana },
  { id: "cherry", label: "Cherry", Icon: Cherry },
  { id: "grape", label: "Grapes", Icon: Grape },
  { id: "carrot", label: "Carrot", Icon: Carrot },
  { id: "citrus", label: "Orange", Icon: Citrus },
  { id: "croissant", label: "Bread", Icon: Croissant },
  { id: "icecream", label: "Ice cream", Icon: IceCream },
  { id: "pizza", label: "Pizza", Icon: Pizza },
  { id: "egg", label: "Egg", Icon: Egg },
  { id: "car", label: "Car", Icon: Car },
  { id: "bus", label: "Bus", Icon: Bus },
  { id: "bike", label: "Bicycle", Icon: Bike },
  { id: "plane", label: "Plane", Icon: Plane },
  { id: "ship", label: "Ship", Icon: Ship },
  { id: "train", label: "Train", Icon: Train },
  { id: "truck", label: "Truck", Icon: Truck },
  { id: "rocket", label: "Rocket", Icon: Rocket },
  { id: "sailboat", label: "Boat", Icon: Sailboat },
  { id: "tractor", label: "Tractor", Icon: Tractor },
  { id: "house", label: "House", Icon: House },
  { id: "bed", label: "Bed", Icon: Bed },
  { id: "lamp", label: "Lamp", Icon: Lamp },
  { id: "sofa", label: "Sofa", Icon: Sofa },
  { id: "door", label: "Door", Icon: DoorOpen },
  { id: "key", label: "Key", Icon: Key },
  { id: "clock", label: "Clock", Icon: Clock },
  { id: "scissors", label: "Scissors", Icon: Scissors },
  { id: "hammer", label: "Hammer", Icon: Hammer },
  { id: "wrench", label: "Wrench", Icon: Wrench },
  { id: "sun", label: "Sun", Icon: Sun },
  { id: "moon", label: "Moon", Icon: Moon },
  { id: "cloud", label: "Cloud", Icon: Cloud },
  { id: "star", label: "Star", Icon: Star },
  { id: "tree", label: "Tree", Icon: Tree },
  { id: "flower", label: "Flower", Icon: Flower },
  { id: "leaf", label: "Leaf", Icon: Leaf },
  { id: "mountain", label: "Mountain", Icon: Mountain },
  { id: "snow", label: "Snow", Icon: Snowflake },
  { id: "umbrella", label: "Umbrella", Icon: Umbrella },
  { id: "heart", label: "Heart", Icon: Heart },
  { id: "phone", label: "Phone", Icon: Phone },
  { id: "book", label: "Book", Icon: Book },
  { id: "camera", label: "Camera", Icon: Camera },
  { id: "music", label: "Music", Icon: Music },
  { id: "gift", label: "Gift", Icon: Gift },
  { id: "anchor", label: "Anchor", Icon: Anchor },
  { id: "crown", label: "Crown", Icon: Crown },
];

export const ICON_MAP: Record<string, IconItem> = Object.fromEntries(
  ICONS.map((i) => [i.id, i]),
);

export const MIN_SEQUENCE = 4;
