import {
  Accessibility,
  Activity,
  AirVent,
  Ambulance,
  Anchor,
  Angry,
  Annoyed,
  Anvil,
  Apple,
  Archive,
  Armchair,
  ArrowDown,
  ArrowDownLeft,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Asterisk,
  Atom,
  AudioLines,
  Award,
  Axe,
  Baby,
  Backpack,
  Balloon,
  Banana,
  Bandage,
  Banknote,
  Bath,
  Battery,
  Beaker,
  Bed,
  Beef,
  Beer,
  Bell,
  Bike,
  Binoculars,
  Bird,
  Blend,
  Blinds,
  Blocks,
  Bluetooth,
  Bolt,
  Bone,
  Book,
  Bookmark,
  Bot,
  Box,
  Brain,
  Briefcase,
  BriefcaseMedical,
  Brush,
  Bug,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Candy,
  Car,
  CarFront,
  Caravan,
  Carrot,
  CassetteTape,
  Castle,
  Cat,
  Cherry,
  Church,
  Circle,
  CircleDashed,
  CircleDot,
  Citrus,
  Clipboard,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudOff,
  CloudRain,
  CloudSnow,
  CloudSun,
  Clover,
  Coffee,
  Cog,
  Coins,
  Compass,
  Cone,
  Construction,
  Cookie,
  CookingPot,
  CornerDownLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Croissant,
  Cross,
  Crosshair,
  Crown,
  CupSoda,
  Cylinder,
  Diamond,
  Dices,
  Disc,
  Disc3,
  Dna,
  Dog,
  DollarSign,
  Donut,
  DoorOpen,
  Drill,
  Droplet,
  Droplets,
  Drum,
  Dumbbell,
  Ear,
  Earth,
  Egg,
  Eraser,
  Euro,
  Eye,
  Factory,
  Fan,
  Feather,
  Fence,
  FileText,
  Fingerprint,
  Fish,
  FishSymbol,
  Flag,
  Flame,
  FlaskConical,
  Flower,
  Flower2,
  Folder,
  Footprints,
  Forklift,
  Frame,
  Frown,
  Fuel,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  GlassWater,
  Glasses,
  Globe,
  Goal,
  Grab,
  Grape,
  Grid2x2,
  Guitar,
  Ham,
  Hammer,
  Hand,
  HandCoins,
  HandHeart,
  Handbag,
  HardDrive,
  HardHat,
  Haze,
  Headphones,
  Heart,
  HeartPulse,
  Hexagon,
  Highlighter,
  Home,
  Hop,
  Hospital,
  Hotel,
  House,
  IceCream,
  IceCreamBowl,
  Inbox,
  Infinity,
  Key,
  Keyboard,
  Lamp,
  LampDesk,
  Landmark,
  Laptop,
  Laugh,
  Leaf,
  Library,
  Lightbulb,
  ListMusic,
  Lock,
  Luggage,
  Magnet,
  Mail,
  Map,
  MapPin,
  Martini,
  Medal,
  Meh,
  Mic,
  Microscope,
  Microwave,
  Milestone,
  Milk,
  Minus,
  Monitor,
  Moon,
  MoonStar,
  Mountain,
  Mouse,
  MoveDown,
  MoveLeft,
  MoveRight,
  MoveUp,
  Music,
  Music2,
  Music3,
  Music4,
  Navigation,
  Notebook,
  Nut,
  Octagon,
  Orbit,
  Origami,
  PaintRoller,
  Palette,
  Palmtree,
  Panda,
  Paperclip,
  PawPrint,
  Pen,
  Pencil,
  Pentagon,
  Percent,
  PersonStanding,
  Phone,
  Piano,
  Pickaxe,
  PiggyBank,
  Pill,
  Pin,
  Pipette,
  Pizza,
  Plane,
  Plug,
  Plus,
  Podcast,
  Pointer,
  Popcorn,
  PoundSterling,
  Presentation,
  Printer,
  Puzzle,
  Pyramid,
  Rabbit,
  Radar,
  Radiation,
  Radio,
  Rainbow,
  Rat,
  Receipt,
  Redo2,
  RefreshCw,
  Refrigerator,
  Repeat,
  Ribbon,
  Rocket,
  RotateCcw,
  RotateCw,
  Route,
  Router,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  SatelliteDish,
  Scale,
  Scan,
  School,
  Scissors,
  Server,
  Shapes,
  Shell,
  Shield,
  ShieldPlus,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shrimp,
  Shuffle,
  Signpost,
  Skull,
  Slash,
  Smartphone,
  Smile,
  SmilePlus,
  Snail,
  Snowflake,
  Sofa,
  Soup,
  Sparkle,
  Sparkles,
  Speaker,
  Spline,
  Sprout,
  Square,
  Squirrel,
  Stamp,
  Star,
  Stars,
  Stethoscope,
  Store,
  Sun,
  SunDim,
  SunMedium,
  Sunrise,
  Sunset,
  Swords,
  Syringe,
  Table,
  Tablet,
  Tablets,
  Tag,
  Target,
  Telescope,
  Tent,
  TestTube,
  Theater,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  Timer,
  Toolbox,
  Tornado,
  Torus,
  TowerControl,
  ToyBrick,
  Tractor,
  Train,
  TrainFront,
  TramFront,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Umbrella,
  Undo2,
  Unlock,
  Usb,
  User,
  UserRound,
  Users,
  Utensils,
  Vault,
  VenetianMask,
  Volleyball,
  Volume2,
  Wallet,
  Warehouse,
  WashingMachine,
  Watch,
  Waves,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Worm,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type CategoryId =
  | "animals"
  | "food"
  | "drinks"
  | "transport"
  | "home"
  | "tools"
  | "nature"
  | "weather"
  | "sports"
  | "music"
  | "tech"
  | "office"
  | "shapes"
  | "arrows"
  | "faces"
  | "body"
  | "clothes"
  | "buildings"
  | "travel"
  | "space"
  | "money"
  | "things"
  | "garden"
  | "medical"
  | "kids";

export type IconItem = {
  id: string;
  label: string;
  Icon: LucideIcon;
  category: CategoryId;
  /** CSS colour value for this icon */
  color: string;
};

export type Category = {
  id: CategoryId;
  label: string;
  Icon: LucideIcon;
  color: string;
};

export const CATEGORIES: Category[] = [
  { id: "animals", label: "Animals", Icon: PawPrint, color: "oklch(0.72 0.12 260)" },
  { id: "food", label: "Food", Icon: Salad, color: "oklch(0.78 0.13 85)" },
  { id: "drinks", label: "Drinks", Icon: Coffee, color: "oklch(0.74 0.12 60)" },
  { id: "transport", label: "Vehicles", Icon: CarFront, color: "oklch(0.7 0.11 230)" },
  { id: "home", label: "Home", Icon: Sofa, color: "oklch(0.74 0.1 300)" },
  { id: "tools", label: "Tools", Icon: Wrench, color: "oklch(0.72 0.09 210)" },
  { id: "nature", label: "Nature", Icon: TreePine, color: "oklch(0.68 0.11 150)" },
  { id: "weather", label: "Weather", Icon: CloudSun, color: "oklch(0.72 0.1 240)" },
  { id: "sports", label: "Sports", Icon: Trophy, color: "oklch(0.74 0.12 40)" },
  { id: "music", label: "Music", Icon: Music, color: "oklch(0.74 0.12 320)" },
  { id: "tech", label: "Tech", Icon: Laptop, color: "oklch(0.7 0.1 250)" },
  { id: "office", label: "Office", Icon: Briefcase, color: "oklch(0.72 0.08 100)" },
  { id: "shapes", label: "Shapes", Icon: Shapes, color: "oklch(0.76 0.1 290)" },
  { id: "arrows", label: "Arrows", Icon: ArrowRight, color: "oklch(0.7 0.09 200)" },
  { id: "faces", label: "Faces", Icon: Smile, color: "oklch(0.8 0.12 80)" },
  { id: "body", label: "Body", Icon: HeartPulse, color: "oklch(0.74 0.11 20)" },
  { id: "clothes", label: "Clothes", Icon: Shirt, color: "oklch(0.76 0.1 340)" },
  { id: "buildings", label: "Buildings", Icon: Building2, color: "oklch(0.7 0.08 270)" },
  { id: "travel", label: "Travel", Icon: Compass, color: "oklch(0.72 0.11 190)" },
  { id: "space", label: "Space", Icon: Orbit, color: "oklch(0.72 0.12 300)" },
  { id: "money", label: "Money", Icon: Coins, color: "oklch(0.78 0.12 95)" },
  { id: "things", label: "Fun Things", Icon: Sparkles, color: "oklch(0.76 0.12 280)" },
  { id: "garden", label: "Garden", Icon: Flower2, color: "oklch(0.7 0.11 135)" },
  { id: "medical", label: "Health", Icon: Stethoscope, color: "oklch(0.74 0.09 175)" },
  { id: "kids", label: "Kids", Icon: ToyBrick, color: "oklch(0.78 0.12 350)" },
];

export const CATEGORY_MAP: Record<CategoryId, Category> = Object.fromEntries(
  CATEGORIES.map((c) => [c.id, c]),
) as Record<CategoryId, Category>;

function make(
  category: CategoryId,
  items: Array<[string, string, LucideIcon]>,
): IconItem[] {
  const color = CATEGORY_MAP[category].color;
  return items.map(([id, label, Icon]) => ({ id, label, Icon, category, color }));
}

export const ICONS: IconItem[] = [
  ...make("animals", [
    ["cat", "Cat", Cat],
    ["dog", "Dog", Dog],
    ["bird", "Bird", Bird],
    ["fish", "Fish", Fish],
    ["rabbit", "Rabbit", Rabbit],
    ["squirrel", "Squirrel", Squirrel],
    ["snail", "Snail", Snail],
    ["bug", "Bug", Bug],
    ["turtle", "Turtle", Turtle],
    ["rat", "Rat", Rat],
    ["bone", "Bone", Bone],
    ["feather", "Feather", Feather],
    ["shell", "Shell", Shell],
    ["worm", "Worm", Worm],
    ["panda", "Panda", Panda],
    ["shrimp", "Shrimp", Shrimp],
    ["origami", "Origami", Origami],
    ["pawprint", "Paw Print", PawPrint],
    ["fishsymbol", "Fish Symbol", FishSymbol],
    ["hop", "Hop", Hop],
  ]),
  ...make("food", [
    ["apple", "Apple", Apple],
    ["banana", "Banana", Banana],
    ["cherry", "Cherry", Cherry],
    ["grape", "Grape", Grape],
    ["carrot", "Carrot", Carrot],
    ["citrus", "Citrus", Citrus],
    ["croissant", "Croissant", Croissant],
    ["icecream", "Ice Cream", IceCream],
    ["pizza", "Pizza", Pizza],
    ["egg", "Egg", Egg],
    ["sandwich", "Sandwich", Sandwich],
    ["soup", "Soup", Soup],
    ["popcorn", "Popcorn", Popcorn],
    ["cookie", "Cookie", Cookie],
    ["donut", "Donut", Donut],
    ["beef", "Beef", Beef],
    ["ham", "Ham", Ham],
    ["wheat", "Wheat", Wheat],
    ["cake", "Cake", Cake],
    ["nut", "Nut", Nut],
  ]),
  ...make("drinks", [
    ["drinks-cupsoda", "Cup Soda", CupSoda],
    ["drinks-wine", "Wine", Wine],
    ["drinks-beer", "Beer", Beer],
    ["drinks-milk", "Milk", Milk],
    ["drinks-martini", "Martini", Martini],
    ["drinks-glasswater", "Glass Water", GlassWater],
    ["drinks-droplet", "Droplet", Droplet],
    ["drinks-blend", "Blend", Blend],
    ["drinks-flaskconical", "Flask Conical", FlaskConical],
    ["drinks-testtube", "Test Tube", TestTube],
    ["drinks-beaker", "Beaker", Beaker],
    ["drinks-candy", "Candy", Candy],
    ["drinks-icecreambowl", "Ice Cream Bowl", IceCreamBowl],
    ["drinks-thermometer", "Thermometer", Thermometer],
    ["drinks-bath", "Bath", Bath],
    ["drinks-torus", "Torus", Torus],
    ["drinks-pipette", "Pipette", Pipette],
    ["drinks-soup", "Soup", Soup],
    ["drinks-coffee", "Coffee", Coffee],
    ["drinks-droplets", "Droplets", Droplets],
  ]),
  ...make("transport", [
    ["car", "Car", Car],
    ["bus", "Bus", Bus],
    ["bike", "Bike", Bike],
    ["plane", "Plane", Plane],
    ["ship", "Ship", Ship],
    ["train", "Train", Train],
    ["truck", "Truck", Truck],
    ["rocket", "Rocket", Rocket],
    ["sailboat", "Sailboat", Sailboat],
    ["tractor", "Tractor", Tractor],
    ["tramfront", "Tram Front", TramFront],
    ["fuel", "Fuel", Fuel],
    ["anchor", "Anchor", Anchor],
    ["caravan", "Caravan", Caravan],
    ["forklift", "Forklift", Forklift],
    ["ambulance", "Ambulance", Ambulance],
    ["route", "Route", Route],
    ["trainfront", "Train Front", TrainFront],
    ["footprints", "Footprints", Footprints],
    ["navigation", "Navigation", Navigation],
  ]),
  ...make("home", [
    ["house", "House", House],
    ["bed", "Bed", Bed],
    ["lamp", "Lamp", Lamp],
    ["sofa", "Sofa", Sofa],
    ["door", "Door Open", DoorOpen],
    ["armchair", "Armchair", Armchair],
    ["refrigerator", "Refrigerator", Refrigerator],
    ["washingmachine", "Washing Machine", WashingMachine],
    ["microwave", "Microwave", Microwave],
    ["blinds", "Blinds", Blinds],
    ["showerhead", "Shower Head", ShowerHead],
    ["cookingpot", "Cooking Pot", CookingPot],
    ["utensils", "Utensils", Utensils],
    ["table", "Table", Table],
    ["lampdesk", "Lamp Desk", LampDesk],
    ["fan", "Fan", Fan],
    ["airvent", "Air Vent", AirVent],
    ["frame", "Frame", Frame],
    ["bath", "Bath", Bath],
    ["sprout", "Sprout", Sprout],
  ]),
  ...make("tools", [
    ["tools-key", "Key", Key],
    ["tools-clock", "Clock", Clock],
    ["tools-scissors", "Scissors", Scissors],
    ["tools-hammer", "Hammer", Hammer],
    ["tools-wrench", "Wrench", Wrench],
    ["tools-drill", "Drill", Drill],
    ["tools-ruler", "Ruler", Ruler],
    ["tools-paintroller", "Paint Roller", PaintRoller],
    ["tools-pickaxe", "Pickaxe", Pickaxe],
    ["tools-axe", "Axe", Axe],
    ["tools-shovel", "Shovel", Shovel],
    ["tools-anvil", "Anvil", Anvil],
    ["tools-magnet", "Magnet", Magnet],
    ["tools-bolt", "Bolt", Bolt],
    ["tools-cog", "Cog", Cog],
    ["tools-brush", "Brush", Brush],
    ["tools-construction", "Construction", Construction],
    ["tools-toolbox", "Toolbox", Toolbox],
    ["tools-lightbulb", "Lightbulb", Lightbulb],
    ["tools-pipette", "Pipette", Pipette],
  ]),
  ...make("nature", [
    ["sun", "Sun", Sun],
    ["moon", "Moon", Moon],
    ["cloud", "Cloud", Cloud],
    ["star", "Star", Star],
    ["tree", "Trees", Trees],
    ["flower", "Flower", Flower],
    ["leaf", "Leaf", Leaf],
    ["mountain", "Mountain", Mountain],
    ["snow", "Snowflake", Snowflake],
    ["umbrella", "Umbrella", Umbrella],
    ["treepine", "Tree Pine", TreePine],
    ["treepalm", "Tree Palm", TreePalm],
    ["sunrise", "Sunrise", Sunrise],
    ["sunset", "Sunset", Sunset],
    ["rainbow", "Rainbow", Rainbow],
    ["waves", "Waves", Waves],
    ["tornado", "Tornado", Tornado],
    ["flame", "Flame", Flame],
    ["clover", "Clover", Clover],
    ["nature-sprout", "Sprout", Sprout],
  ]),
  ...make("weather", [
    ["weather-cloudrain", "Cloud Rain", CloudRain],
    ["weather-cloudsnow", "Cloud Snow", CloudSnow],
    ["weather-cloudlightning", "Cloud Lightning", CloudLightning],
    ["weather-cloudsun", "Cloud Sun", CloudSun],
    ["weather-cloudmoon", "Cloud Moon", CloudMoon],
    ["weather-cloudfog", "Cloud Fog", CloudFog],
    ["weather-clouddrizzle", "Cloud Drizzle", CloudDrizzle],
    ["weather-cloudhail", "Cloud Hail", CloudHail],
    ["weather-wind", "Wind", Wind],
    ["weather-thermometer", "Thermometer", Thermometer],
    ["weather-haze", "Haze", Haze],
    ["weather-moonstar", "Moon Star", MoonStar],
    ["weather-sunmedium", "Sun Medium", SunMedium],
    ["weather-sundim", "Sun Dim", SunDim],
    ["weather-snowflake", "Snowflake", Snowflake],
    ["weather-umbrella", "Umbrella", Umbrella],
    ["weather-droplets", "Droplets", Droplets],
    ["weather-zap", "Zap", Zap],
    ["weather-sunrise", "Sunrise", Sunrise],
    ["weather-cloudoff", "Cloud Off", CloudOff],
  ]),
  ...make("sports", [
    ["sports-dumbbell", "Dumbbell", Dumbbell],
    ["sports-bike", "Bike", Bike],
    ["sports-trophy", "Trophy", Trophy],
    ["sports-medal", "Medal", Medal],
    ["sports-volleyball", "Volleyball", Volleyball],
    ["sports-goal", "Goal", Goal],
    ["sports-target", "Target", Target],
    ["sports-timer", "Timer", Timer],
    ["sports-flag", "Flag", Flag],
    ["sports-footprints", "Footprints", Footprints],
    ["sports-waves", "Waves", Waves],
    ["sports-tent", "Tent", Tent],
    ["sports-mountain", "Mountain", Mountain],
    ["sports-swords", "Swords", Swords],
    ["sports-crosshair", "Crosshair", Crosshair],
    ["sports-activity", "Activity", Activity],
    ["sports-heartpulse", "Heart Pulse", HeartPulse],
    ["sports-snowflake", "Snowflake", Snowflake],
    ["sports-rocket", "Rocket", Rocket],
    ["sports-zap", "Zap", Zap],
  ]),
  ...make("music", [
    ["music-music", "Music", Music],
    ["music-music2", "Music 2", Music2],
    ["music-music3", "Music 3", Music3],
    ["music-music4", "Music 4", Music4],
    ["music-guitar", "Guitar", Guitar],
    ["music-piano", "Piano", Piano],
    ["music-drum", "Drum", Drum],
    ["music-mic", "Mic", Mic],
    ["music-headphones", "Headphones", Headphones],
    ["music-radio", "Radio", Radio],
    ["music-speaker", "Speaker", Speaker],
    ["music-disc", "Disc", Disc],
    ["music-disc3", "Disc 3", Disc3],
    ["music-audiolines", "Audio Lines", AudioLines],
    ["music-volume2", "Volume 2", Volume2],
    ["music-listmusic", "List Music", ListMusic],
    ["music-podcast", "Podcast", Podcast],
    ["music-cassettetape", "Cassette Tape", CassetteTape],
    ["music-bell", "Bell", Bell],
    ["music-tv", "Tv", Tv],
  ]),
  ...make("tech", [
    ["tech-laptop", "Laptop", Laptop],
    ["tech-smartphone", "Smartphone", Smartphone],
    ["tech-tablet", "Tablet", Tablet],
    ["tech-monitor", "Monitor", Monitor],
    ["tech-keyboard", "Keyboard", Keyboard],
    ["tech-mouse", "Mouse", Mouse],
    ["tech-printer", "Printer", Printer],
    ["tech-cpu", "Cpu", Cpu],
    ["tech-harddrive", "Hard Drive", HardDrive],
    ["tech-server", "Server", Server],
    ["tech-router", "Router", Router],
    ["tech-wifi", "Wifi", Wifi],
    ["tech-bluetooth", "Bluetooth", Bluetooth],
    ["tech-battery", "Battery", Battery],
    ["tech-plug", "Plug", Plug],
    ["tech-usb", "Usb", Usb],
    ["tech-camera", "Camera", Camera],
    ["tech-watch", "Watch", Watch],
    ["tech-gamepad2", "Gamepad 2", Gamepad2],
    ["tech-bot", "Bot", Bot],
  ]),
  ...make("office", [
    ["office-book", "Book", Book],
    ["office-notebook", "Notebook", Notebook],
    ["office-pencil", "Pencil", Pencil],
    ["office-pen", "Pen", Pen],
    ["office-paperclip", "Paperclip", Paperclip],
    ["office-pin", "Pin", Pin],
    ["office-folder", "Folder", Folder],
    ["office-filetext", "File Text", FileText],
    ["office-calendar", "Calendar", Calendar],
    ["office-clipboard", "Clipboard", Clipboard],
    ["office-highlighter", "Highlighter", Highlighter],
    ["office-eraser", "Eraser", Eraser],
    ["office-calculator", "Calculator", Calculator],
    ["office-briefcase", "Briefcase", Briefcase],
    ["office-archive", "Archive", Archive],
    ["office-inbox", "Inbox", Inbox],
    ["office-mail", "Mail", Mail],
    ["office-stamp", "Stamp", Stamp],
    ["office-bookmark", "Bookmark", Bookmark],
    ["office-presentation", "Presentation", Presentation],
  ]),
  ...make("shapes", [
    ["shapes-circle", "Circle", Circle],
    ["shapes-square", "Square", Square],
    ["shapes-triangle", "Triangle", Triangle],
    ["shapes-hexagon", "Hexagon", Hexagon],
    ["shapes-pentagon", "Pentagon", Pentagon],
    ["shapes-diamond", "Diamond", Diamond],
    ["shapes-octagon", "Octagon", Octagon],
    ["shapes-star", "Star", Star],
    ["shapes-heart", "Heart", Heart],
    ["shapes-spline", "Spline", Spline],
    ["shapes-shapes", "Shapes", Shapes],
    ["shapes-cylinder", "Cylinder", Cylinder],
    ["shapes-cone", "Cone", Cone],
    ["shapes-box", "Box", Box],
    ["shapes-pyramid", "Pyramid", Pyramid],
    ["shapes-torus", "Torus", Torus],
    ["shapes-grid2x2", "Grid 2x 2", Grid2x2],
    ["shapes-slash", "Slash", Slash],
    ["shapes-minus", "Minus", Minus],
    ["shapes-plus", "Plus", Plus],
  ]),
  ...make("arrows", [
    ["arrows-arrowup", "Arrow Up", ArrowUp],
    ["arrows-arrowdown", "Arrow Down", ArrowDown],
    ["arrows-arrowleft", "Arrow Left", ArrowLeft],
    ["arrows-arrowright", "Arrow Right", ArrowRight],
    ["arrows-arrowupright", "Arrow Up Right", ArrowUpRight],
    ["arrows-arrowdownleft", "Arrow Down Left", ArrowDownLeft],
    ["arrows-moveup", "Move Up", MoveUp],
    ["arrows-movedown", "Move Down", MoveDown],
    ["arrows-moveleft", "Move Left", MoveLeft],
    ["arrows-moveright", "Move Right", MoveRight],
    ["arrows-cornerupright", "Corner Up Right", CornerUpRight],
    ["arrows-cornerdownleft", "Corner Down Left", CornerDownLeft],
    ["arrows-refreshcw", "Refresh Cw", RefreshCw],
    ["arrows-rotatecw", "Rotate Cw", RotateCw],
    ["arrows-rotateccw", "Rotate Ccw", RotateCcw],
    ["arrows-undo2", "Undo 2", Undo2],
    ["arrows-redo2", "Redo 2", Redo2],
    ["arrows-shuffle", "Shuffle", Shuffle],
    ["arrows-repeat", "Repeat", Repeat],
    ["arrows-milestone", "Milestone", Milestone],
  ]),
  ...make("faces", [
    ["faces-smile", "Smile", Smile],
    ["faces-frown", "Frown", Frown],
    ["faces-meh", "Meh", Meh],
    ["faces-laugh", "Laugh", Laugh],
    ["faces-angry", "Angry", Angry],
    ["faces-annoyed", "Annoyed", Annoyed],
    ["faces-smileplus", "Smile Plus", SmilePlus],
    ["faces-ghost", "Ghost", Ghost],
    ["faces-skull", "Skull", Skull],
    ["faces-baby", "Baby", Baby],
    ["faces-user", "User", User],
    ["faces-users", "Users", Users],
    ["faces-userround", "User Round", UserRound],
    ["faces-personstanding", "Person Standing", PersonStanding],
    ["faces-glasses", "Glasses", Glasses],
    ["faces-eye", "Eye", Eye],
    ["faces-ear", "Ear", Ear],
    ["faces-hand", "Hand", Hand],
    ["faces-thumbsup", "Thumbs Up", ThumbsUp],
    ["faces-thumbsdown", "Thumbs Down", ThumbsDown],
  ]),
  ...make("body", [
    ["body-hand", "Hand", Hand],
    ["body-handheart", "Hand Heart", HandHeart],
    ["body-grab", "Grab", Grab],
    ["body-pointer", "Pointer", Pointer],
    ["body-thumbsup", "Thumbs Up", ThumbsUp],
    ["body-footprints", "Footprints", Footprints],
    ["body-eye", "Eye", Eye],
    ["body-ear", "Ear", Ear],
    ["body-brain", "Brain", Brain],
    ["body-heartpulse", "Heart Pulse", HeartPulse],
    ["body-bone", "Bone", Bone],
    ["body-fingerprint", "Fingerprint", Fingerprint],
    ["body-accessibility", "Accessibility", Accessibility],
    ["body-personstanding", "Person Standing", PersonStanding],
    ["body-baby", "Baby", Baby],
    ["body-smile", "Smile", Smile],
    ["body-scan", "Scan", Scan],
    ["body-activity", "Activity", Activity],
    ["body-dna", "Dna", Dna],
    ["body-pill", "Pill", Pill],
  ]),
  ...make("clothes", [
    ["clothes-shirt", "Shirt", Shirt],
    ["clothes-footprints", "Footprints", Footprints],
    ["clothes-glasses", "Glasses", Glasses],
    ["clothes-watch", "Watch", Watch],
    ["clothes-crown", "Crown", Crown],
    ["clothes-backpack", "Backpack", Backpack],
    ["clothes-briefcase", "Briefcase", Briefcase],
    ["clothes-shoppingbag", "Shopping Bag", ShoppingBag],
    ["clothes-umbrella", "Umbrella", Umbrella],
    ["clothes-gem", "Gem", Gem],
    ["clothes-ribbon", "Ribbon", Ribbon],
    ["clothes-venetianmask", "Venetian Mask", VenetianMask],
    ["clothes-hardhat", "Hard Hat", HardHat],
    ["clothes-wallet", "Wallet", Wallet],
    ["clothes-scissors", "Scissors", Scissors],
    ["clothes-sparkles", "Sparkles", Sparkles],
    ["clothes-handbag", "Handbag", Handbag],
    ["clothes-zap", "Zap", Zap],
    ["clothes-shovel", "Shovel", Shovel],
    ["clothes-sparkle", "Sparkle", Sparkle],
  ]),
  ...make("buildings", [
    ["buildings-building", "Building", Building],
    ["buildings-building2", "Building 2", Building2],
    ["buildings-hotel", "Hotel", Hotel],
    ["buildings-store", "Store", Store],
    ["buildings-factory", "Factory", Factory],
    ["buildings-church", "Church", Church],
    ["buildings-castle", "Castle", Castle],
    ["buildings-hospital", "Hospital", Hospital],
    ["buildings-school", "School", School],
    ["buildings-landmark", "Landmark", Landmark],
    ["buildings-warehouse", "Warehouse", Warehouse],
    ["buildings-fence", "Fence", Fence],
    ["buildings-towercontrol", "Tower Control", TowerControl],
    ["buildings-tent", "Tent", Tent],
    ["buildings-home", "Home", Home],
    ["buildings-mappin", "Map Pin", MapPin],
    ["buildings-milestone", "Milestone", Milestone],
    ["buildings-theater", "Theater", Theater],
    ["buildings-library", "Library", Library],
    ["buildings-stethoscope", "Stethoscope", Stethoscope],
  ]),
  ...make("travel", [
    ["travel-map", "Map", Map],
    ["travel-mappin", "Map Pin", MapPin],
    ["travel-compass", "Compass", Compass],
    ["travel-globe", "Globe", Globe],
    ["travel-luggage", "Luggage", Luggage],
    ["travel-ticket", "Ticket", Ticket],
    ["travel-camera", "Camera", Camera],
    ["travel-palmtree", "Palmtree", Palmtree],
    ["travel-backpack", "Backpack", Backpack],
    ["travel-binoculars", "Binoculars", Binoculars],
    ["travel-navigation", "Navigation", Navigation],
    ["travel-plane", "Plane", Plane],
    ["travel-hotel", "Hotel", Hotel],
    ["travel-sunset", "Sunset", Sunset],
    ["travel-tent", "Tent", Tent],
    ["travel-signpost", "Signpost", Signpost],
    ["travel-route", "Route", Route],
    ["travel-flag", "Flag", Flag],
    ["travel-mountain", "Mountain", Mountain],
    ["travel-waves", "Waves", Waves],
  ]),
  ...make("space", [
    ["space-rocket", "Rocket", Rocket],
    ["space-star", "Star", Star],
    ["space-moon", "Moon", Moon],
    ["space-sun", "Sun", Sun],
    ["space-orbit", "Orbit", Orbit],
    ["space-satellite", "Satellite", Satellite],
    ["space-satellitedish", "Satellite Dish", SatelliteDish],
    ["space-telescope", "Telescope", Telescope],
    ["space-sparkle", "Sparkle", Sparkle],
    ["space-sparkles", "Sparkles", Sparkles],
    ["space-atom", "Atom", Atom],
    ["space-radar", "Radar", Radar],
    ["space-globe", "Globe", Globe],
    ["space-moonstar", "Moon Star", MoonStar],
    ["space-radiation", "Radiation", Radiation],
    ["space-circledashed", "Circle Dashed", CircleDashed],
    ["space-earth", "Earth", Earth],
    ["space-zap", "Zap", Zap],
    ["space-circledot", "Circle Dot", CircleDot],
    ["space-stars", "Stars", Stars],
  ]),
  ...make("money", [
    ["money-dollarsign", "Dollar Sign", DollarSign],
    ["money-euro", "Euro", Euro],
    ["money-poundsterling", "Pound Sterling", PoundSterling],
    ["money-banknote", "Banknote", Banknote],
    ["money-coins", "Coins", Coins],
    ["money-creditcard", "Credit Card", CreditCard],
    ["money-wallet", "Wallet", Wallet],
    ["money-piggybank", "Piggy Bank", PiggyBank],
    ["money-receipt", "Receipt", Receipt],
    ["money-shoppingcart", "Shopping Cart", ShoppingCart],
    ["money-shoppingbag", "Shopping Bag", ShoppingBag],
    ["money-store", "Store", Store],
    ["money-gem", "Gem", Gem],
    ["money-percent", "Percent", Percent],
    ["money-tag", "Tag", Tag],
    ["money-landmark", "Landmark", Landmark],
    ["money-handcoins", "Hand Coins", HandCoins],
    ["money-trendingup", "Trending Up", TrendingUp],
    ["money-scale", "Scale", Scale],
    ["money-vault", "Vault", Vault],
  ]),
  ...make("things", [
    ["heart", "Heart", Heart],
    ["phone", "Phone", Phone],
    ["book", "Book", Book],
    ["camera", "Camera", Camera],
    ["music", "Music", Music],
    ["gift", "Gift", Gift],
    ["things-anchor", "Anchor", Anchor],
    ["crown", "Crown", Crown],
    ["bell", "Bell", Bell],
    ["flag", "Flag", Flag],
    ["award", "Award", Award],
    ["shield", "Shield", Shield],
    ["lock", "Lock", Lock],
    ["unlock", "Unlock", Unlock],
    ["puzzle", "Puzzle", Puzzle],
    ["infinity", "Infinity", Infinity],
    ["asterisk", "Asterisk", Asterisk],
    ["things-star", "Star", Star],
    ["ticket", "Ticket", Ticket],
    ["sparkles", "Sparkles", Sparkles],
  ]),
  ...make("garden", [
    ["garden-flower", "Flower", Flower],
    ["garden-flower2", "Flower 2", Flower2],
    ["garden-sprout", "Sprout", Sprout],
    ["garden-leaf", "Leaf", Leaf],
    ["garden-treedeciduous", "Tree Deciduous", TreeDeciduous],
    ["garden-shovel", "Shovel", Shovel],
    ["garden-bug", "Bug", Bug],
    ["garden-bird", "Bird", Bird],
    ["garden-sun", "Sun", Sun],
    ["garden-droplet", "Droplet", Droplet],
    ["garden-fence", "Fence", Fence],
    ["garden-apple", "Apple", Apple],
    ["garden-wheat", "Wheat", Wheat],
    ["garden-clover", "Clover", Clover],
    ["garden-trees", "Trees", Trees],
    ["garden-rabbit", "Rabbit", Rabbit],
    ["garden-snail", "Snail", Snail],
    ["garden-carrot", "Carrot", Carrot],
    ["garden-cherry", "Cherry", Cherry],
    ["garden-watch", "Watch", Watch],
  ]),
  ...make("medical", [
    ["medical-stethoscope", "Stethoscope", Stethoscope],
    ["medical-pill", "Pill", Pill],
    ["medical-syringe", "Syringe", Syringe],
    ["medical-bandage", "Bandage", Bandage],
    ["medical-thermometer", "Thermometer", Thermometer],
    ["medical-heart", "Heart", Heart],
    ["medical-heartpulse", "Heart Pulse", HeartPulse],
    ["medical-cross", "Cross", Cross],
    ["medical-ambulance", "Ambulance", Ambulance],
    ["medical-briefcasemedical", "Briefcase Medical", BriefcaseMedical],
    ["medical-microscope", "Microscope", Microscope],
    ["medical-testtube", "Test Tube", TestTube],
    ["medical-dna", "Dna", Dna],
    ["medical-brain", "Brain", Brain],
    ["medical-bone", "Bone", Bone],
    ["medical-hospital", "Hospital", Hospital],
    ["medical-activity", "Activity", Activity],
    ["medical-eye", "Eye", Eye],
    ["medical-tablets", "Tablets", Tablets],
    ["medical-shieldplus", "Shield Plus", ShieldPlus],
  ]),
  ...make("kids", [
    ["kids-baby", "Baby", Baby],
    ["kids-toybrick", "Toy Brick", ToyBrick],
    ["kids-puzzle", "Puzzle", Puzzle],
    ["kids-blocks", "Blocks", Blocks],
    ["kids-gamepad2", "Gamepad 2", Gamepad2],
    ["kids-dices", "Dices", Dices],
    ["kids-rocket", "Rocket", Rocket],
    ["kids-ticket", "Ticket", Ticket],
    ["kids-candy", "Candy", Candy],
    ["kids-icecream", "Ice Cream", IceCream],
    ["kids-cake", "Cake", Cake],
    ["kids-bike", "Bike", Bike],
    ["kids-palette", "Palette", Palette],
    ["kids-drum", "Drum", Drum],
    ["kids-star", "Star", Star],
    ["kids-smile", "Smile", Smile],
    ["kids-rabbit", "Rabbit", Rabbit],
    ["kids-train", "Train", Train],
    ["kids-balloon", "Balloon", Balloon],
    ["kids-crown", "Crown", Crown],
  ]),
];

export const ICON_MAP: Record<string, IconItem> = Object.fromEntries(
  ICONS.map((i) => [i.id, i]),
);

export const MIN_SEQUENCE = 4;

/** A sequence must span at least this many different picture groups. */
export const MIN_CATEGORIES = 2;

export function sequenceCategories(sequence: string[]): CategoryId[] {
  const seen = new Set<CategoryId>();
  for (const id of sequence) {
    const item = ICON_MAP[id];
    if (item) seen.add(item.category);
  }
  return [...seen];
}

/** Returns an error message when the sequence breaks a rule, else null. */
export function sequenceError(sequence: string[]): string | null {
  if (sequence.length < MIN_SEQUENCE) {
    return `Pick at least ${MIN_SEQUENCE} pictures.`;
  }
  if (sequenceCategories(sequence).length < MIN_CATEGORIES) {
    return `Use pictures from at least ${MIN_CATEGORIES} different groups.`;
  }
  return null;
}
